---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: windows-2008r2
    communicator: winrm

suites:
  - name: server
    data_bags_path: "test/integration/server/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/server/encrypted_data_bag_secret"
    attributes:
      sql_server:
        accept_eula: true
        sysadmins: ['vagrant']
        server_sa_password: "gp*W-HX8qX"
        version: "2012"
        update_enabled: false
      octopus:
        server:
          data_bag: "octopus_test"
          sql_dbname: "octopus_test"
          authentication_type: "UsernamePassword"
    run_list:
      - recipe[ms_dotnet::ms_dotnet4]
      - recipe[sql_server::server]
      - recipe[octopus::server]
  - name: tentacle
    run_list:
      - recipe[octopus::install_tentacle]
